name: say_hello
on:
  push

jobs:
  job_name: say_hello
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Greeting Message
        run: echo "Hello, world"
